version: '3'
services:
  mongo:
    image: mongo
    container_name: mongo    
    ports:
      - "27017:27017"
  api:
    build: 
      context: ./      
      dockerfile: Dockerfile-Api
    image: urlzinha-api
    depends_on:
      - mongo
    ports:
      - 3000:3000
    environment:
      - MONGO_URL=mongo://mongo
      - SERVER_PORT=3000
    command:
      sh -c 'npm i && node server.js'
  web:
    build:
      context: ./
      dockerfile: Dockerfile-Web
      args:
        VUE_APP_API_URL : http://localhost:3000
    image: urlzinha-web
    depends_on:
      - api
    ports:
      - 8080:80
    